#!/usr/bin/env bash
# install HAproxy service into server as load balancer between two web servers
# web-01 3.83.253.154
# web-02 52.91.133.125

sudo apt-get install --no-install-recommends -y software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y
sudo apt-get install haproxy=2.8.\* -y
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo touch /etc/haproxy/haproxy.cfg
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
echo "frontend web-front
        mode http
        bind *:80
        default_backend web-backend
	option h1-case-adjust-bogus-client

backend web-backend
        mode http
        balance roundrobin
        server 280474-web-01 3.83.253.154:80 check
        server 280474-web-02 52.91.133.125:80 check

global
        h1-case-adjust x-served-by X-Served-By
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
sudo service haproxy start
