#!/usr/bin/env bash
# install HAproxy service into server as load balancer between two web servers
# web-01 3.83.253.154
# web-02 52.91.133.125

sudo apt-get update
sudo apt install haproxy -y
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo touch /etc/haproxy/haproxy.cfg
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
echo "balance roundrobin" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "server web01 3.83.253.154:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "server web02 52.91.133.125 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
