#!/usr/bin/env bash
# server nginx debugging
sudo sed -i '21s/.*/\tlisten *:80;/' /etc/nginx/sites-enabled/default
sudo sed -i '22s/.*//' /etc/nginx/sites-enabled/default
sudo sed -i '21s/.*/\tlisten *:80;/' /etc/nginx/sites-available/default
sudo sed -i '22s/.*//' /etc/nginx/sites-available/default
sudo service nginx restart
