#!/usr/bin/env bash
# server nginx debugging
sudo sed -i '21s/.*/\tlisten 80 default_server;/' /etc/nginx/sites-enabled/default
sudo sed -i '22s/.*/\tlisten [::]:80 default_server;/' /etc/nginx/sites-enabled/default
sudo sed -i '21s/.*/\tlisten 80 default_server;/' /etc/nginx/sites-available/default
sudo sed -i '22s/.*/\tlisten [::]:80 default_server;/' /etc/nginx/sites-available/default
sudo service nginx restart
