#!/usr/bin/env bash
# server nginx debugging
sudo sed -i 's/8080 default_server/80 default_server/g' /etc/nginx/sites-available/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo service nginx restart

