#!/usr/bin/env bash
# script to make another file, infinte while loop, signals handling
echo $$ >> /var/run/myscript.pid
trap "echo I hate the kill command; rm -rf /var/run/myscript.pid; exit" SIGTERM
trap "rm -rf /var/run/myscript.pid; exit" SIGQUIT
trap "echo Y U no love me?!" SIGINT
while :
do 
   echo "To infinity and beyond"
   sleep 2
done
