#!/usr/bin/env bash
# script to manage "manage_my_process" file

if [[ $# -eq 0 ]]
then
    echo "Usage: manage_my_process {start|stop|restart}"

elif [[ "$1" != "start" && "$1" != "stop" && "$1" != "restart" ]]; then
    echo "Usage: manage_my_process {start|stop|restart}"

elif [[ "$1" = "start" ]]; then
     ./manage_my_process &
     echo $! >> /var/run/my_process.pid
     echo "manage_my_process started"

elif [[ "$1" = "stop" ]]; then
     pkill -f "./manage_my_process"
     rm -fr /var/run/my_process.pid
     rm -fr /tmp/my_process
     echo "manage_my_process stopped"

elif [[ "$1" = "restart" ]]; then
     pkill -f "./manage_my_process"
     rm -fr /var/run/my_process.pid
     rm -fr /tmp/my_process
     ./manage_my_process &
     echo $! >> /var/run/my_process.pid
     echo "manage_my_process restarted"
fi

