#!/usr/bin/env bash
# script that displays To infinity and beyond indefinitely and trap sigterm signal.

trap "echo I am invincible!!!" SIGTERM
while :
do
   echo "To infinity and beyond"
   sleep 2
done
