#!/usr/bin/env bash
# test checking for a file school
file="school"
if [ -e $file ]; then
  echo "$file file exists"
  if [ -s $file ]; then
     echo "$file file is not empty"
  else
     echo "$file file is empty"
  fi
  if [ -f $file ]; then
     echo "$file is a reglar file"
  fi
else
     echo "$file file does not exist"
fi
