#!/usr/bin/env bash
# test checking for a file school
if [ -e ./school ]; then
  echo "school file exists"
  if ! [ -s ./school ]; then
     echo "school file is empty"
  elif [ -s ./school ]; then
     echo "school file is not empty"
  fi
  if [ -f ./school ]; then
     echo "school is a reglar file"
  fi
else
     echo "school file does not exist"
fi
